### ISSUE TITLE
Test for Michael

### ISSUE THREAD

**Issue by mpathiuk** [Wiredcraft/test-pm#13]
First make sure you read the test guidelines here: https://github.com/Wiredcraft/test-pm

This task will be followed up asynchronously over a few days and should not take more than two hours in total.

**Project Introduction**
You have been assigned as project manager for a project for the client Zbal Corp (your client stakeholder is Vincent). The outcome of this project will be a web app which allows a user to sign up, and log-in to a system that gives them a data dashboard for climate figures. The system as a whole is expected in 5 weeks.

**Project Details**
The work has been divided into two parts:
• the backend and frontend for login and signup as well as the frontend for climate data display - This will be handled by Wiredcraft completely
• the backend for climate data information which will be provided by a separate company Qingfeng Labs, you will need to interface with Song, their project manager, to coordinate as they are building this system from scratch for Zbal Corp.

The specific requirements for the registration have been decided as Username, Password and Email address fields. The login will be based on username. And after sign up the real-time climate data system expects to receive the Username and Email so they can customise the information in the backend for WCL to access and display in the front-end the correct data for this user.

In your team you have:
• Two designers who can make mockups and flow diagrams of the login and once confirmed, implement the frontend parts and dashboard.
• A developer who can implement the backend and help out integrating the login/data dashboard figure frontend
• A dev-ops engineer who can set up the servers and take care of deployment.

**Your Task**

The first step of this task is for you to provide the following:

• Clarify the requirements and provide your understanding of the **final scope** for Wiredcraft's work.
• An initial **project plan** including:
- A work breakdown for Wiredcraft's integration with Qingfeng Labs up to the final delivery
- a rough timeline of what you think needs to happen in this project and deliverables. You can use the methodology of your choice for this plan.
- Outline the project phases you would have and what should be delivered at each phase. 
- The plan can be a few paragraphs of text and the timeline can also be made using Github markdown by outlining what needs to be done during each week.
- A rough outline of the process you would use for the day-to-day organisation of the development team and a short overview of how you would manage the communication flows internally and externally. 

You can also kick off with any questions to multiple people in one GitHub comment, I will answer likewise and bring up more cases to test your communication skills as we go along:
(Assume you have already been introduced to the client (@Vincent1211) and real-time climate data service vendor (@Song222) ) and you can @myteam333 for questions to your development team)

e.g.
@flfrank222 - Hi there, can I confirm with you the requirements for ...
@Vincent1211 - I heard from Song2222 that they need to have xxx, does that mean we need to change ....
@myteam333 - I'm not clear on how xxx could work, can you tell me more about it?
@mpathiuk - For the test, I don't understand what you mean by xxx ...

**Comment by mikelhsia** [comment]
@mpathiuk 
Hi Mik, for the test, could you kindly explain me what does "WCL" stand for?

**Comment by mikelhsia** [comment]
@vincent1211 
Hi Vincent, I have received a brief introduction of the project, which is to build a climate dashboard for registered user to check out the climate figures. However, if you can tell me a little bit more about the goal of this project, or who are the target audience of the web app, I believe we could clarify the requirements of this web site to better meet the goal of the project.

Furthermore, design-wise, do you have any preferable website to showcase us what would be the ideal style we should take into consideration?

Lastly, have you purchased the domain name of this website, and where you would like host your web app? This is quite crucial since if you want to host the website inside China, you are obligated to apply ICP beian number. 

Thank you very much.

**Comment by mikelhsia** [comment]
@song2222
Hi Song, Nice to work with you. Since we're going to integrate with the system that you're currently building, could you quickly walk me through the plan and would be appreciated if you can let me know the items in the list below:
1. Could you provide an estimation of when are we able to connect to your platform and start retrieving data from the platform?
2. What format could we get those data from the platform? 
3. When would you be able to share a documentation regarding the details of the way to retrieve data? 
Since we have only five weeks to finish this web app, it would be great if we can get the documentation earlier so that we could start planning ahead.

Thanks,

**Comment by mikelhsia** [comment]
@myteam333
Dear all, 
It's my pleasure to work with you. Please see below for the brief project introduction:
## Deliverable
The outcome of this project will be a web app which allows a user to sign up, and log-in to a system that gives them a data dashboard for climate figures. 

## Duration
The system as a whole is expected in 5 weeks.

## Project Detail
The work has been divided into two parts:
• the backend and frontend for login and signup as well as the frontend for climate data display - This will be handled by Wiredcraft completely
• the backend for climate data information which will be provided by a separate company Qingfeng Labs, you will need to interface with Song, their project manager, to coordinate as they are building this system from scratch for Zbal Corp.
The specific requirements for the registration have been decided as Username, Password and Email address fields. The login will be based on username. And after sign up the real-time climate data system expects to receive the Username and Email so they can customise the information in the backend for WCL to access and display in the front-end the correct data for this user.

I'm working with the client now to finalize the project requirements with more details, as for the design and mockup, I'm asking client and see is there is any website that we can refer to. Since this is my first project here, is there anything you might need from the client to start with the mockup?

And for the development, I'm contacting Qingfeng at the moment and see if we can get any idea or documentation regarding the integration. Could you quickly let me know, that base on the information provided, what technology stack would seem to be a fit for this project?

I'm also working on the project plan and the schedule as long as I gather more information from the client. Let's do a kick-off meeting as soon as I've gather more detail from the client.

Let me know if you have any question.
Cheers,

**Comment by mpathiuk** [comment]
Hi @mikelhsia ,

1. WCL is the short-form of our company name :) Wiredcraft Limited
2. From @vincent1211 : 
- goal of this project: Mainly to give easy access to climate data for our different agencies
- target audience: Technically proficient users who know how to search and find the appropriate data already.
- design wise we'll go with whatever you suggest
- We've handed over our domain credentials and have ICP already for that domain
3. From @song2222
- We've  already sent your team the API specs, we'll have our staging system up in 2 weeks ready for your integration and 2 weeks after that we'll be ready for production.
- Everything will be in Json format, and the specs are finalised.
4. From @myteam333
- We've received the specs from Qingfeng Labs and they seem good enough for us to start work, we've selected the JS tech stack for this project. We think we can have staging ready in 3 weeks and prod a week after that.
- We've worked with the client and have the initial wireframes confirmed by them

**Comment by mikelhsia** [comment]
# Project requirements and work of scope
A registered-member-only platform with the following requirements:
- Using username, email, password as required information for registration, where username as unique key for user records
- Successful registration triggers sending email to system admin, reminding admin to configure the right data to present to that specific user
- A dashboard page for user to search/view the appropriate data
- Integration with 3rd party API to retrieve data from their end on regular basis.

**Comment by mikelhsia** [comment]
Hi @mpathiuk,
Does the word "**they**" in this requirement "_And after sign up the real-time climate data system expects to receive the Username and Email so **they** can customise the information in the backend for WCL to ..._" mean website administrator from Zbal Corp where they will manage the user information from backend without our assistant?

Thank you,

**Comment by mikelhsia** [comment]
# Initial Project Plan
### WCL and Qingfeng Integration breakdown
- API testing
- Feedback testing results to Qingfeng to see whether all APIs work as in the API spec
- API integrating fetching data for front-end to display
- Production integration testing as a whole 

### Project Timeline
- **Week 1**: _Design and getting client approval_
    - Kick-off meeting to brief the team with client's requirement
    - Design and deliver mockup for client to get approval
    - Start with login/registration functionality following the requirements
    - **Deliverable**: Mockup for client
- **Week 2**: _Backend development and front end development _
    - API testing and collaborating with QingFeng to see how the API works (Backend)
    - Start integrating API in order to fetch data from QingFeng (Backend)
    - After getting mockup design approved by client, apply basic styling through out the website (Front end)
- **Week 3**: _Backend development and front end development_
    - Email trigger after registration functionality and necessary backend configuration panel (Backend)
    - Dashboard styling (Front end)
    - Visualize data from QingFeng according to mockup and design (Front end)
- **Week 4**: _Deployment, review, and QA_
    - Deploy alpha version
    - Testing QingFeng production API
    - Internal QA testing 
    - Internal review meeting
    - **Deliverable**: Alpha for client to try out the prototype
- **Week 5**: _Review and preparation for staging to production_
    - External review meeting with stakeholders
    - Getting feedback from client and address the issues reported by client
    - Deploy production web app
    - **Deliverable**: production web app

### Day-to-Day Communication
Using agile methodology
Everyday morning 15~20 minutes to know the following items:
- What have been done
- What's the plan today
- What're the obstacle that need me to communicate with client
- What other risks that we encounter while implementing the features and QingFeng integration

By getting general idea and progress from internal team, I'll be able to convey what's the progress and what other things we still need stakeholders' inputs in timely manner.

**Comment by mpathiuk** [comment]
@mikelhsia 
> Does the word "they" in this requirement "And after sign up the real-time climate data system expects to receive the Username and Email so they can customise the information in the backend for WCL to ..." mean website administrator from Zbal Corp where they will manage the user information from backend without our assistant?

Assume this will be automated, matching users to a list on their side for special privileges or a default setup if they are not on the list

We're in week 2 of the project, when Vincent from Zbal Corp gets back to you:
- We just became aware of a new industry regulation that requires us to ask for user's physical address during registration and verify this somehow. We have a system that can automatically send out a mail by postage and I've attached the API specs. We would need this within the same timeline

After talking through the flows your team tells you they can implement the address verification
using an automated mail, they would send a mail using the automated system to the given address with a 6 digit code, once received the user can use this to continue registration. It is doable, however it would add 1 week to the timeline. 

What would you do next.

**Comment by mikelhsia** [comment]
Before I do anything, I would go over the contract or any other project scope related documentation in order to define whether this would consider a change request.

I would first tell the client in a polite way that this was not included in the original project scope, which we consider a change request. However, in order to meet the deadline, we would require additional resources to speed up the development.

Then I'll forward this new industry regulation to QingFeng immediately, and see whether they could also speed up the development so that we could get production ready faster.

Thirdly, I would inform internal stakeholders the same message and see whether development team could spare more resources on this project for a week so that we could speed up and meet the deadline. After internal discussion and made the decision all together, then I'll quickly drafted an updated timeline and send to all stakeholders. If we could not solve with internal resources, then I'll also inform client that our development wouldn't be able to accept this change request, but we could definitely put full resources on this spec right after we finish current project scope.

**Comment by mpathiuk** [comment]
Thanks @mikelhsia we have what we need from this test. You will hear back from us in the next few working days.

Closing as done.
