### ISSUE TITLE
Test for Jeremy

### ISSUE THREAD

**Issue by mpathiuk** [Wiredcraft/test-pm#16]
First make sure you read the test guidelines here: https://github.com/Wiredcraft/test-pm

This task will be followed up asynchronously over a few days and should not take more than two hours in total.

**Project Introduction**
On behalf of Wiredcraft (WCL), you have been assigned as project manager for a project for the client Kuno Corp (your client stakeholder is Leo). The outcome of this project will be a Wechat miniapp which allows a user to sign up and pay for membership to a coupon system. The system as a whole is expected in 9 weeks.

**Project Details**
The work has been divided into two parts:
• the backend and frontend for wechat miniapp signup (which requires the user to pay a yearly fee of 100 rmb) as well as the frontend for coupon information - This will be handled by Wiredcraft completely
• the backend for coupon information which will be provided by a separate company Jhonny Labs, you will need to interface with Frank, their project manager, to coordinate as they are building this system from scratch for Kuno Corp.

The specific requirements for the registration have been decided as the default Wechat authentication and WCL will need to store Username and location fields, at the last stage of signup the user needs to pay 100 rmb from their Wechat wallet for 1 year of membership. The login for existing users will be Wechat authentication as usual. And after sign up the coupin information system expects to receive the Username and location so they can customise the coupon information in their backend for WCL to access and display in the front-end.

In your team you have:
• Two frontend developeres who can make mockups and flow diagrams and once confirmed, implement the frontend parts.
• A developer who can implement the WCL backend and help out integrating the coupons frontend with the coupons backend
• A dev-ops engineer who can set up the servers and take care of deployment.

**Your Task**

The first step of this task is for you to provide the following:

• Clarify the requirements and provide your understanding of the **final scope** for Wiredcraft's work.
• An initial **project plan** including:
- A work breakdown for Wiredcraft's integration with Jhonny Labs up to the final delivery
- a rough timeline of what you think needs to happen in this project and deliverables. You can use the methodology of your choice for this plan.
- Outline the project phases you would have and what should be delivered at each phase. 
- The plan can be a few paragraphs of text and the timeline can also be made using Github markdown by outlining what needs to be done during each week.
- A rough outline of the process you would use for the day-to-day organisation of the development team and a short overview of how you would manage the communication flows internally and externally. 

You can also kick off with any questions to multiple people in one GitHub comment, I will answer likewise and bring up more cases to test your communication skills as we go along:
(Assume you have already been introduced to the client (@leo111) and the coupons service vendor (@flfrank222) ) and you can @myteam333 for questions to your development team)

e.g.
@flfrank222 - Hi there, can I confirm with you the requirements for ...
@leo111 - I heard from FLFrank222 that they need to have xxx, does that mean we need to change ....
@myteam333 - I'm not clear on how xxx could work, can you tell me more about it?
@mpathiuk - For the test, I don't understand what you mean by xxx ...

**Comment by notjeremyhissong** [comment]
@mpathiuk Thanks for the overview. Just want to clarify how deep into the interpersonal communication side you'd like me to go for this. If I were starting an actual conversation with Frank in this context, it would be helpful to first have a bit of background about why Jhonny Labs was selected to provide the coupon backend for this project (was this WCL's decision, Kuno Corp's decision, or a collective decision?)

Below is a high-level overview, intentionally leaning towards the vague side as it progresses, since the latter sprints will depend on results and feedback from the earlier stages.

Although there are some pieces of the backend that our developers can work on right off the bat, a portion of it will depend on the timely delivery of the coupon backend from Frank's team. For the overall timeline I outlined below, I assumed that Frank says his team can get their part completed by the beginning of Week 4, although in reality this part of the plan would depend on his response and timeline.

A couple of other quick questions –
1. Is Wiredcraft responsible for maintaining any portion of this project after it has been deployed, or will the project be fully complete after the final deliverable is approved as done?
2. Assuming this product will be released in the mainland Chinese market, I just want to confirm that it is legal to deploy a system that collects users' signup and money without having the user go through a Real Name Verification process. I'm not sure if WeChat authorization can suffice for RNV purposes (could you clarify?), but especially if the final product contains any pathways for users to rate coupons/stores, ideally I'd like to confirm compliance up front to avoid regulatory delays down the road.

In general, I would stick to an open and transparent communication strategy as much as possible:

Day to Day Organisation
- Daily scrum meetings
- Encourage quick and efficient in-person communication whenever possible
- Create chat group to keep everyone updated

Internal Communications
- Clear issue tracking on Github
- Ongoing communication throughout workday and ad-hoc meetings as needed

External Communications
- Regular progress updates with Leo
- Follow up meetings/conversations with Frank and his team to ensure smooth integration with their backend

---

@flfrank222 - Hi Frank, looking forward to working with you on this project. As we confirm our development plan, I'd like to make sure that our team is in line with the timeline on your end. I understand that Wiredcraft will be handling the frontend and backend for the WeChat side, and that we will connect with your coupon system backend once it is ready. If you have a minute this afternoon, could we can jump on a quick call to discuss timeline and next steps? If you have some documentation in the meantime for the coupon backend pieces, please share and I will circulate with our dev team.

---

@myteam333 - Looking forward to working with you all on this project. To get started, I'd like to clarify the overall requirements from our client (Kuno Corp) and propose a rough timeline for the coming weeks, and we can discuss in more depth tomorrow at our kickoff meeting.

Our goal is to create a WeChat miniapp for Kuno Corp which allows users to pay a membership fee in order to access coupons. Wiredcraft will handle frontend and backend development of the WeChat miniapp, and Frank and the team at Jhonny Labs will handle building out the backend for coupon information.

We're looking at an overall timeline of 9 weeks. Here is what I'd propose to get us started, and of course we will continue to revise as needed along the way during each sprint planning:

***PHASE 1: Project Kickoff***

**Week 1**
- JH (that's me): Meet with Leo (from Kuno Corp) to ensure clear understanding of Kuno's requirements and project scope
- JH: Meet with Frank (from Jhonny Labs) to discuss timeline requirements for connecting to the coupon system backend and clarify specs
- All team: Project overview meeting to introduce requirements, go through any questions, and discuss any concerns or considerations upfront as we work towards confirming more specific requirements and project timeline

Once these tasks have been completed:
- JH: Draft detailed timeline and task lists for the project, work with WCL team to review and verify, and circulate with Leo and Frank for confirmation
- JH: Refine the remaining parts of the project plan and backlog according to feedback and requirements from team members and client


***PHASE 2: Coding & Development Iteration***

**Week 2**
- Frontend/Design: draft wireframes and flow mockups (deliver mockups by the end of the week that we can share with Leo).
- Backend/Dev: begin development of WeChat registration and member info backend

**Week 3**
- JH: Meet with Leo to discuss flow mockups
- Frontend Dev: start building out frontend based on Leo's feedback
- Backend Dev: complete WeChat registration and member info backend (deliver working code for this part by end of the week)

**Week 4**
-  Dev team: Connect backend/frontend interface for WeChat registration and member info (deliver a working prototype of the registration/payment parts by the end of the week that we can share with Leo)
- Backend Dev: liaise with Frank to initiate connection to coupon system backend

**Week 5**
- Backend Dev: complete connection and test coupon system backend
- Frontend Dev: complete frontend for coupon information parts (deliver working prototype of coupon system by the end of the week that we can share with Leo)


***PHASE 3: Revision, Testing and Release***

**Week 6**
- Testing and debugging of internal WCL components
- Testing and debugging of connection to coupon backend from Jhonny Labs

**Week 7**
- Full working prototype given to Leo
- Internal testing by Kuno
- Revisions and debugging

**Week 8**
- Beta testing with closed user group (@mpathiuk Would this part normally be managed by Kuno or by Wiredcraft? Let me know if I should go into more detail about UAT.)
- Revisions and debugging

**Week 9**
- Project complete

**Comment by mpathiuk** [comment]
Hi @jeremyhissong .

>Just want to clarify how deep into the interpersonal communication side you'd like me to go for this. 

That's up to you, but I'd keep this to getting the information you need and not getting into the account management level.

> it would be helpful to first have a bit of background about why Jhonny Labs was selected to provide the coupon backend for this project (was this WCL's decision, Kuno Corp's decision, or a collective decision?)

Kuno Corp already chose this provider based on previous work with them


> 1. Is Wiredcraft responsible for maintaining any portion of this project after it has been deployed, or will the project be fully complete after the final deliverable is approved as done?

We'll handover to Kuno Corp's IT team as part of delivery and htey will run maintenance operations.

> 2. Assuming this product will be released in the mainland Chinese market, I just want to confirm that it is legal to deploy a system that collects users' signup and money without having the user go through a Real Name Verification process. I'm not sure if WeChat authorization can suffice for RNV purposes (could you clarify?), but especially if the final product contains any pathways for users to rate coupons/stores, ideally I'd like to confirm compliance up front to avoid regulatory delays down the road.

Good catch but you don't need to worry about this for the moment.


Assume you have approval for the plan and agreement with Kuno corp and Jhonny Labs. Also assume that your tech team received the API specs and had several calls with Jhonny Labs to solidify the integration work.

**Comment by mpathiuk** [comment]
You're in week 5 of your plan when Leo gets back to you:
From Leo111
Hi there, We have some feedback from upper management on the mockups and we need to change some of the frontend styling. Please see attached our pdf of the necessary changes

After running these past your team you discover that changing these will need 1 more week of work and will push back the delivery timeline by 1 week.

What do you do next?

**Comment by notjeremyhissong** [comment]
@mpathiuk Noted, thank you. In general I would be direct with the timeline required, and would propose a few possible pathways for Kuno Corp to choose from depending on their situation and needs.

If there is disagreement amongst the WCL team about how long the new frontend changes should take, we may consider doing a group estimation in a planning poker or wideband delphi process (as you suggested) in order to ensure that our timeline is accurate. Assuming that our timeline is confirmed to take 1 additional week, I would reply to Leo with something like this:

---

@Leo111
Thank you for the feedback. We have looked over the changes and will be able to implement the updated styles with one additional week of work time added to the project. Given this situation, we have a few options:

Option 1: Adjust the project timeline to accommodate the updated frontend style requirements. This will allow us to complete all requested features and deliver a stable product with an additional week of development time. If you can afford a slight delay, this would probably be our most efficient and least costly option.

Option 2: Continue with the previous frontend styles (for now) to keep things on schedule for a timely release. Once the initial version has been completed, we will work towards an updated version with new frontend styles according to the recent management feedback. This option will take some extra effort as we'll need to double back on the frontend parts, but it will allow us to deliver a viable working product according to the original timeline.

Option 3: If the updated frontend styles are essential to your business needs and you cannot afford a delay, I will investigate options for bringing some additional hands onto this project. If you would like to go this route, please let me know and I will check to see what would be doable on our end. Note that this option would require a higher cost to support the added staffing and overtime work.

Please let me know your preference and we will proceed accordingly. Feel free to call or message if you'd like to discuss further.

---

@mpathiuk I'm not sure how feasible this would be since I haven't seen the PDF of requested changes from Kuno Corp's management, but if there is a way to address some of their concerns through other frontend tweaks, we could also discuss this with the WCL team and present a couple of alternative frontend options to Kuno Corp that could be implemented more quickly without delaying the project by a week. If we have any trusted outsource providers (possibly Jhonny Labs) who can help with certain development pieces, that could also be worth exploring if Kuno Corp decides they'd like to press ahead with option 3 and our resources at WCL are stretched thin.

**Comment by mpathiuk** [comment]
Thanks @jeremyhissong , we have enough information to proceed. Closing this test as completed.
