### ISSUE TITLE
Test for Andrew

### ISSUE THREAD

**Issue by mpathiuk** [Wiredcraft/test-pm#3]
First make sure you read the test guidelines here: https://github.com/Wiredcraft/test-pm

This task will be followed up asynchronously over a few days and should not take more than two hours in total.

**Project Introduction**
You have been assigned as project manager for a project for the client Hodor Corp (your client stakeholder is Harry). The outcome of this project will be a website which allows a user to sign up, and log-in to a system that gives them stock market information. The system as a whole is expected in 5 weeks.

**Project Details**
The work has been divided into two parts:
• the backend and frontend for login and signup - This will be handled by Wiredcraft completely
• the backend and frontend for stock information which will be provided by a separate company Frodo Labs, you will need to interface with Frank, their project manager, to coordinate as they are building this system from scratch for Hodor Corp.

The specific requirements for the registration have been decided as Username, Password and Email address fields. The login will be based on username. And after sign up the stock market information system expects to receive the Username and Email so they can customise the information.

In your team you have:
• A designer who can make mockups and flow diagrams of the login and once confirmed, implement the frontend
• A developer who can implement the backend and help out integrating the login frontend
• A dev-ops engineer who can set up the servers and take care of deployment.

**Your Task**

The first step of this task is for you to provide the following:

• Clarify the requirements and provide your understanding of the **final scope** for Wiredcraft's work.
• An initial **project plan** including:
- A work breakdown for Wiredcraft's integration with Frodo labs up to the final delivery
- a rough timeline of what you think needs to happen in this project and deliverables. You can use the methodology of your choice for this plan,
- Outline the project phases you would have and what should be delivered at each phase. 
- The plan can be a few paragraphs of text and the timeline can also be made using Github markdown by outlining what needs to be done during each week.
- A rough outline of the process you would use for the day-to-day organisation of the development team and a short overview of how you would manage the communication flows internally and externally. 

You can also kick off with any questions to multiple people in one GitHub comment, I will answer likewise and bring up more cases to test your communication skills as we go along:
(Assume you have already been introduced to the client (@hcharry111) and stock market service vendor (@flfrank222) ) and you can @myteam333 for questions to your development team)

e.g.
@flfrank222 - Hi there, can I confirm with you the requirements for ...
@hcharry111 - I heard from FLFrank222 that they need to have xxx, does that mean we need to change ....
@myteam333 - I'm not clear on how xxx could work, can you tell me more about it?
@mpathiuk - For the test, I don't understand what you mean by xxx ...

**Comment by AndyGreene** [comment]
@myteam333 - hi guys,  do you need any additional resources for testing? Particularly integration testing with stock information from Frodo Corp?
@flfrank222 - Hi Frank, can I just confirm with you, username and email is the only user information you need passed on to you? 
@myteam333 - I'm not quite clear on the infrastructure needed for system deployment and integration with Frodo Corp, please could you go through it with me. 

Project Scope: 
• Wiredcraft will create a system sign up functionality. User sign-up fields: Username, Password, Email Address
• Wiredcraft will build a system login functionality based on Username 
• Wiredcraft will integrate with Frodo Labs by passing on user sign up information (Username and Email) 

Initial Project Plan:

Initiation 
• Introduce myself to project stakeholders Harry and Frank. Explain how they can contact me, and how they can track project progress and offer guidance using Github. 
• Send project scope document to Harry and Frank, ask for confirmation. 
• Draw up a standard list of non-functional requirements and send to Harry and Frank for confirmation. 
• Draw up a system integration testing plan and send to Frank for revision 
• Set out common rules regarding new change requirements and send to Harry for confirmation 

Planning
• Add items to product backlog as follows:
 Mock-up design of user UI and UX (this must be sent to client for confirmation at earliest date) 
 Backend design and test for login and sign up 
 Frontend design and test for login and signup 
 Integration testing at our end 
 Integration testing with Frodo Labs

• Check calendar of team members over the next 5 weeks to ensure availability
• Meet with team to clarify back log items, split up items into manageable tasks and help assign tasks to each of the team members.  Agree with them on a definition of done for each of the tasks. Ask team to provide time estimates for task items. 
• Based on time estimates, agree on project timeline and schedule team member’s times in calendar 
• Communicate ETC of deliverables to Frank. Based on this, confirm suitable date for integration testing with Frodo Labs.
• Update Harry on timeline for completion of key deliverables

Execution 
• As the team work through the backlog, track project progress on Github. Ask team members to update task status in terms of Tasks to Do, Work in Progress, Ready to Be Tested and Done. Ask team members to update the ETC for their tasks after each day. Track planned vs current estimates on a burndown chart.  
• Host daily meetings for team members in order to understand task progress and any impediments for team members. Offer as much support as possible to reduce impediments.  
• After back log items have been completed (excluding final integration testing and release), ask team to present each of the items to product manager. 

Release
• Once reviewed, send Frodo Labs a release of our software for them to test integration, and also receive a release of their software for us to test integration. 
• After integration testing has been completed, ask dev-ops to release software to client. 

Notes: I felt it was better not to use Scrum cycles because the team is small in number and not much opportunity for overlapping task completion

**Comment by mpathiuk** [comment]
• From @myteam333 - Nothing more needed for testing from our side for the current acceptance criteria.
• From @flfrank222 - It shouldn't change after now as far as we can see. 

Ok, so the plan is in progress and it is now the middle of week 2. The mockups were finished and approved by both stakeholders. Your developer has started on the integration already and spent 3 days on it. You get the following messages:

From @ flfrank222:
Hi @AndyGreene , our specification has changed a little due to incoming requirements on our side, for your integration you'll need to ask the user for address and you'll need to send that to us as well. It can be one plaintext field added to the registration form. Is that possible without changing the schedule? We've cleared this with Harry from HodorCorp already, this is an incoming requirement due to changing legislature that requires us to keep this information.

From @ hcharry111 :
Hi @AndyGreene - We just had a security audit on our side and when you deliver the system, we also need you to send us your internal IP addresses of all users, you don't need to store them, just pass them along to the FrodoLabs endpoints as part of every request. This shouldn't be a lot of work right? That's now a security requirement on our side.

**Comment by AndyGreene** [comment]
Hi guys, I would proceed with the following actions: 
- Set up a group call with Frank and Harry to understand the new requirements, i.e. confirm with Harry that the user address is needed in the integration, confirm with Frank the requirement to send Internal IP addresses to FrodoLabs. 
- Draw up a spec for the new requirements
- Explain to Frank and Harry, that I must get time estimates from the team and we may need to extend the timelines and charge for the extra hours. 
- Send the spec to the team and set up a meeting with them to clarify any questions on the new requirements and revised integration (go back to Harry and Frank if necessary). Work with the team to set up time estimates for it and any rework that must be done based on the new requirements 
- Check with senior staff if there are any legal implications for sending internal IP addresses of all users to FrodoLabs
- Based on the time estimates, check the time availability of the team to complete the work, update the project timelines accordingly.  
- If the work is substantial (more than a half a day), explain to Harry that we must charge for the additional work (add it to the initial invoice), ask him for sign off of the new requirements  
- Contact Frank to confirm we will move on with the new requirements
- Send the revised project timelines to all stakeholders and our team 
- Add all additional work to the Project Backlog

**Comment by mpathiuk** [comment]
Thanks for this @AndyGreene ,we have what we need from the test to proceed. Closing the test as done and moving on the internal evaluation.
