### ISSUE TITLE
Test for FuZhuang

### ISSUE THREAD

**Issue by mpathiuk** [Wiredcraft/test-pm#4]
First make sure you read the test guidelines here: https://github.com/Wiredcraft/test-pm

This task will be followed up asynchronously over a few days and should not take more than two hours in total.

Project Introduction
You have been assigned as project manager for a project for the client Hodor Corp (your client stakeholder is Harry). The outcome of this project will be a website which allows a user to sign up, and log-in to a system that gives them stock market information. The system as a whole is expected in 5 weeks.

Project Details
The work has been divided into two parts:
• the backend and frontend for login and signup - This will be handled by Wiredcraft completely
• the backend and frontend for stock information which will be provided by a separate company Frodo Labs, you will need to interface with Frank, their project manager, to coordinate as they are building this system from scratch for Hodor Corp.

The specific requirements for the registration have been decided as Username, Password and Email address fields. The login will be based on username. And after sign up the stock market information system expects to receive the Username and Email so they can customise the information.

In your team you have:
• A designer who can make mockups and flow diagrams of the login and once confirmed, implement the frontend
• A developer who can implement the backend and help out integrating the login frontend
• A dev-ops engineer who can set up the servers and take care of deployment.

Your Task

The first step of this task is for you to provide the following:

• Clarify the requirements and provide your understanding of the final scope for Wiredcraft's work.
• An initial project plan including:

A work breakdown for Wiredcraft's integration with Frodo labs up to the final delivery
a rough timeline of what you think needs to happen in this project and deliverables. You can use the methodology of your choice for this plan,
Outline the project phases you would have and what should be delivered at each phase.
The plan can be a few paragraphs of text and the timeline can also be made using Github markdown by outlining what needs to be done during each week.
A rough outline of the process you would use for the day-to-day organisation of the development team and a short overview of how you would manage the communication flows internally and externally.
You can also kick off with any questions to multiple people in one GitHub comment, I will answer likewise and bring up more cases to test your communication skills as we go along:
(Assume you have already been introduced to the client (@hcharry111) and stock market service vendor (@flfrank222) ) and you can @myteam333 for questions to your development team)

e.g.
@flfrank222 - Hi there, can I confirm with you the requirements for ...
@hcharry111 - I heard from FLFrank222 that they need to have xxx, does that mean we need to change ....
@myteam333 - I'm not clear on how xxx could work, can you tell me more about it?
@mpathiuk - For the test, I don't understand what you mean by xxx ...

**Comment by fuzhuangli** [comment]
@mpathiuk For the test， is hcharry111 the product owner？Will the product owner provide a function feature list or our team will need to deliver a function specification？

**Comment by mpathiuk** [comment]
You can see hcharry111 as the Project sponsor and main stakeholder. He's provided you the basic requirements, and you're not expected to go into a lot of detail, more of a high level work breakdown to gauge your experience in analysing project steps/deliverables and differentiating work items.

**Comment by fuzhuangli** [comment]
Requirement understanding
1. Background

- Purpose: To build the user account module for the stock information website and allow website to present different contents to users based on user profile

- Value: Enable the website to customize the content to users and accumulate user profile data for future use

2. Requirement scope
Wiredcaft will need to build the account module and enable it to interact with the master module of the stock information website. A rough breakdown of the function features as follows:

- User profile management function（what fields will the user be able to edit after they log in）
- User sign-up function（registration）
- User log in function
- Email verification function
- Password recovery function
- safety mechanism 
- API with master module

3. Open questions

- whether the listed function features is sufficient from the client's point of view-will chat with the client to confirm；
- Whether the current identified fields in user profile is sufficient for the master module for content differentiation-will chat with Frodo to confirm

**Comment by fuzhuangli** [comment]
For the test，the waterfall method I'm currently use in my current position，the rough timeline （milestones）would be:

Week1 Day2 
Confirmation of function specs with Team and client and Frodo lab project manager，assuming feature items aligned as：
- User profile management function（what fields will the user be able to edit after they log in）
- User sign-up function（registration）
- User log in function
- Email verification function
- Password recovery function
- safety mechanism
Deliverable: Function specification document

Week 2 Day3 
Confirmation of user case and UI design for all all features with the team and client
Deliverable: User case doc and UI design doc

Week2 Day 5 
Confirmation of technical design with the team
Deliverable: Technical design doc，including API definitions

Week4 Day 2
Smoke test for main features and user flows，starting API testing with master module with Frodo labs
Deliverable: email confirmation of smoke test pass

Week4 Day5
All features dev finished and tested，including API testing with master module with Frodo labs
Deliverable: Testing doc

Week5 Day2 
UAT confirmation by client
Deliverable: email to confirm UAT pass

Week5 Day 5
Lauch and deployment to production
Deliverable: Online functioning module

After project， review meeting and records

**Comment by fuzhuangli** [comment]
I would try to produce a scrum version of the plan later today，with what I learned from the scrum training

**Comment by fuzhuangli** [comment]
Scrum plan

Phase\Timeline\Content\Deliverables

- Sprint Planing\Week 1\Clarify requirements and confirm work items，inviting all team members and stakeholders\Function feature list for the user account module
- Sprint Planning \Week1\Sprint Planning meeting follow-up---Estimate sprint budget and work item cost（in hrs），agree on Sprint backlog\Sprint backlog；breakdown to daily tasks
- Sprint \Week 1 -Week3\ Use burndown chart to track progress of work items & daily tasks completed. Finish all initial functional development and unit tests at the end of week 3\Burndown chart；Design&Technical documentation； Functioning pages for sign-up， log in and password recovery and etc.
- Sprint \Week 4\Integration test\Burntdown chart；Testing documentation
- Sprint \Week 5\UAT & Launch\Burntdown chart； UAT&Dev-op documentation
- Sprint Review\Week 5\Celebrate sprint competition and review lessons learned in this sprint


Daily communication routine:

- 30 mins Standup meeting every morning: Each member of the dev team will summarize what he did yesterday, what he will do today and what’s the barriers he encountered and what help he might need.
- Update burndown chart at the end of the day by each dev member

Organization of communication

- In general situations，I would be using group chat for updating information with relevant parties （usually there would be a chat group for internal teams and a separate one with teams plus external stakeholders including client and contract partners or etc.） so that all members in the group could follow up the thread without repeating the same information. For complex issues，a conference call would be set up so people could align on decisions and agree on action items concerning the complex issue.
- Important conclusions and action items lists will be posted as reminders and visible to all related parties.
- In specific circumstances，I might also talk to individuals separately so that the same action\decision could be accepted by presenting them on appropriate ways

**Comment by fuzhuangli** [comment]
@hcharry111 Hi there，from our initial communication，currently we would need your feedback on 2 issues:
1. Function features specification:
here's summary from our discussion yesterday:
- User profile management function（what fields will the user be able to edit after they log in）
- User sign-up function（registration）
- User log in function
- Email verification function
- Password recovery function
As far as we understand you want a simple and standard version for this part，is this list in line with your expectation？ Pls let us know we you have more things in your mind.

2. Would you be able to provide an estimate of the average and peak daily user visit of the website you expected？We would need to set up performance indicators for the website functioning test.

@flfrank222 On our sprint planning meeting yesterday，we've specified that the fields for user account profile will be the following:
- Username
- Password
- Email address
Could you kindly confirm that these fields  are sufficient for our integration of the master module function from your side？

**Comment by mpathiuk** [comment]
Follow up questions covered during interview. Closing as completed. Thanks for participating @fuzhuangli .
